const Map<String, String> viVN = {
  'meeting.header.title': 'Lịch họp sắp tới',
  'meeting.header.date': 'Thứ Hai, 29 Tháng 03, 2026',
  'meeting.delete.action': 'Xóa',
  'meeting.detail.title': 'Chi tiết cuộc họp',
  'meeting.detail.label_title': 'Tiêu đề',
  'meeting.detail.label_time': 'Thời gian',
  'meeting.detail.label_duration': 'Thời lượng',
  'meeting.detail.label_location': 'Địa điểm',
  'meeting.detail.label_platform': 'Nền tảng',
  'meeting.detail.label_attendees': 'Người tham dự',
  'meeting.detail.label_status': 'Trạng thái',
  'meeting.detail.label_organizer': 'Tổ chức',
  'common.close': 'Đóng',
  'meeting.delete.tooltip': 'Xóa lịch họp',
  'meeting.delete.confirm_title': 'Xác nhận xóa',
  'meeting.delete.confirm_content': 'Bạn có chắc muốn xóa lịch họp này không?',
  'common.cancel': 'Hủy',
  'meeting.delete.success_title': 'Đã xóa',
  'meeting.delete.success_content': 'Lịch họp đã được xóa.',
  'meeting.create.title': 'Tạo cuộc họp mới',
  'meeting.create.hint_title': 'Tiêu đề cuộc họp',
  'meeting.create.pick_date': 'Chọn ngày',
  'meeting.create.pick_time': 'Chọn giờ',
  'meeting.create.hint_duration': 'Thời lượng (VD: 90 phút)',
  'meeting.create.pick_location': 'Chọn địa điểm',
  'meeting.create.hint_organizer': 'Người tổ chức (tùy chọn)',
  'meeting.create.save': 'Lưu cuộc họp',
  'meeting.create.missing_title': 'Thiếu thông tin',
  'meeting.create.missing_content':
      'Vui lòng nhập đủ tiêu đề, ngày, giờ, địa điểm và thời lượng.',
  'meeting.status_new': 'MỚI',
  'meeting.attendees_suffix': 'người',
  'nav.overview': 'Tổng quan',
  'nav.business': 'Nghiệp vụ',
  'nav.chat': 'Trao đổi',
  'nav.profile': 'Cá nhân',
  'app_title': 'GB Lãnh Đạo',
  'tasks_title': 'Giao việc & KPI',
  'search_hint': 'Tìm kiếm công việc, hồ sơ...',
  'view_detail': 'Xem chi tiết',
  'progress': 'Tiến độ',
};
